back_bunter/urls.py
from django.contrib import admin
from django.urls import path
from bunter_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contato/', views.contato, name='contato'),
    path('produtos/', views.produto, name='produto'),
    path('sobre_mim/', views.sobre_mim, name='sobre_mim'),
    path('compra/', views.compra, name='compra'),
    path('cadastro_cliente/', views.CadastroCliente, name='cadastro_clientes'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bunter_app/models.py
from django.db import models

class Contact(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    titulo = models.CharField(max_length=200)
    mensagem = models.TextField()
    
    def __str__(self):
        return self.titulo

class Cliente(models.Model):  # Renomeado para seguir a convenção de nomenclatura
    nome = models.CharField(max_length=30, blank=False, null=False)
    sobrenome = models.CharField(max_length=30, blank=False, null=False)
    cpf = models.CharField(max_length=14, blank=False, null=False, unique=True)  # Adicionado unique=True
    email = models.EmailField(blank=False, null=False)
    
    def __str__(self):
        return f"{self.nome} {self.sobrenome}"

class Marca(models.Model):  # Renomeado para seguir a convenção de nomenclatura
    nome = models.CharField(max_length=30, blank=False, null=False)  # Renomeado para nome

    def __str__(self):
        return self.nome

class Produto(models.Model):
    codigo = models.CharField(max_length=10, unique=True)
    descricao = models.CharField(max_length=70)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    custo = models.DecimalField(max_digits=8, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=8, decimal_places=2)
    imagem = models.ImageField(upload_to='imagens/', blank=False, null=False)
    
    def __str__(self):
        return self.descricao
    
class Venda(models.Model):  # Renomeado para seguir a convenção de nomenclatura
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    produtos = models.ManyToManyField(Produto)  # Alterado para ManyToManyField para permitir vários produtos por venda
    total_compra = models.DecimalField(max_digits=8, decimal_places=2, blank=False, null=False)
    
    def __str__(self):
        return self.cliente



bunter_app/forms.py
from django import forms
from .models import Cliente
from .models import Contact

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'sobrenome', 'cpf', 'email']

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['nome', 'email', 'titulo', 'mensagem']

bunter_app/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from .forms import ContatoForm
from .forms import ClienteForm
from .models import Produto

# Create your views here.
def home(request):
    return render(request, 'homes/home.html')
def contato(request):
    if request.method == 'POST':
        formContact = ContatoForm(request.POST)
        if formContact.is_valid():
            formContact.save()
            return redirect('home')  
    else:
        formContact = ContatoForm()
    return render(request, 'contato/contatos.html', {'form': formContact})
        
def produto(request):
    produtos = Produto.objects.all()
    return render(request, 'produtos/produtos.html', {'produtos': produtos})
def sobre_mim(request):
    return render(request, 'sobre_mim/sobre_mim.html')
def compra(request):
    return render(request, 'compra/compra.html')

def CadastroCliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)  
        if form.is_valid():
            form.save()
            return redirect('produto')
    else:
        form = ClienteForm()
    return render(request, 'cadastro_cliente/cliente.html', {'form': form})

bunter_app/templates/cadastro_cliente/cliente.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content />
    <meta name="author" content />
    <title>Bunter</title>
    <link rel="shortcut icon" href="{% static 'homes/img/bunter_logo.png' %}" type="image/x-icon">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link rel="stylesheet" href="{% static 'cliente/stylecss/cadastroCliente.css' %}">
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
        rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- boostrap_css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'contato/stylecss/cont_estilo.css' %}"> -->
</head>

<body class="d-flex flex-column">
    <main class="flex-shrink-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'homes/img/bunter_logo.png' %}"
                        width="65em" height="65em" class="d-inline-block align-top" alt="logo bunter_logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'sobre_mim' %}">Sobre a loja</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'produto' %}">Produtos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contato' %}">contato</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <div class="container">
    <h1 class="mt-5">Cadastro de Cliente</h1>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nome">Nome:</label>
            {{ form.nome }}
        </div>
        <div class="form-group">
            <label for="id_sobrenome">Sobrenome:</label>
            {{ form.sobrenome }}
        </div>
        <div class="form-group">
            <label for="id_cpf">CPF:</label>
            <input type="text" class="form-control" id="id_cpf" name="cpf" maxlength="14" placeholder="Digite seu CPF">
            <small id="cpf-error" class="text-danger d-none">CPF inválido</small> <!-- Mensagem de erro oculta -->
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>
    </main>

    <footer class="bg-white py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0">Copyright &copy; Your Website 2023</div></div>
                <div class="col-auto">
                    <a class="small" href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>

    <!-- js do projeto -->
    <script src="{% static 'cliente/scripts/validarCPF.js' %}"></script>

    <!-- Inclua os arquivos JS do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

bunter_app/templates/compra/compra.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content />
    <meta name="author" content />
    <title>Bunter</title>
    <link rel="shortcut icon" href="{% static 'homes/img/bunter_logo.png' %}" type="image/x-icon">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
        rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- boostrap_css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'contato/stylecss/cont_estilo.css' %}"> -->
</head>

<body class="d-flex flex-column">
    <main class="flex-shrink-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'homes/img/bunter_logo.png' %}"
                        width="65em" height="65em" class="d-inline-block align-top" alt="logo bunter_logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'sobre_mim' %}">Sobre a loja</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'produto' %}">Produtos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contato' %}">contato</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <h1 class="mt-5">Cadastro de Vendas</h1>
            <form method="POST" action="{% url 'compra' %}" class="mt-4">
                {% csrf_token %}
                <div class="form-group">
                    <label for="cliente">Cliente:</label>
                    <select id="cliente" name="cliente" class="form-control" required>
                        <option value="" disabled selected>Selecione o cliente</option>
                        {% for cliente in clientes %}
                        <option value="{{ cliente.id }}">{{ cliente.nome }} {{ cliente.sobrenome }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="produtos">Produtos:</label>
                    <select id="produtos" name="produtos" class="form-control" multiple required>
                        {% for produto in produtos %}
                        <option value="{{ produto.id }}">{{ produto.descricao }} - {{ produto.marca.nome }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="quantidade">Quantidade:</label>
                    <input type="number" id="quantidade" name="quantidade" class="form-control" min="1" required>
                </div>
                <div class="form-group">
                    <label for="valor_total">Valor Total:</label>
                    <input type="number" id="valor_total" name="valor_total" class="form-control" step="0.01" required>
                    <br>
                </div>
                <button type="submit" class="btn btn-primary">Cadastrar Venda</button>
            </form>
        </div>
    </main>
    <footer class="bg-white py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0">Copyright &copy; Your Website 2023</div>
                </div>
                <div class="col-auto">
                    <a class="small" href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Adicione os links para os arquivos JavaScript do Bootstrap e seu arquivo de scripts personalizados aqui -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="scripts.js"></script>
</body>

</html>

bunter_app/templates/contato/contatos.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content />
    <meta name="author" content />
    <title>Bunter</title>
    <link rel="shortcut icon" href="{% static 'homes/img/bunter_logo.png' %}" type="image/x-icon">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
        rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- boostrap_css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'contato/stylecss/cont_estilo.css' %}"> -->
</head>

<body class="d-flex flex-column">
    <main class="flex-shrink-0">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'homes/img/bunter_logo.png' %}"
                        width="65em" height="65em" class="d-inline-block align-top" alt="logo bunter_logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'sobre_mim' %}">Sobre a loja</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'produto' %}">Produtos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contato' %}">Contato</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container">
                <div class="row align-items-stretch justify-content-center no-gutters">
                    <div class="col-md-7">
                        <div class="container">
                            <h2>Formulário de Contato</h2>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome:</label>
                                    <input type="text" class="form-control" id="id_nome" name="nome">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">Email:</label>
                                    <input type="email" class="form-control" id="id_email" name="email">
                                </div>
                                <div class="form-group">
                                    <label for="id_titulo">Título:</label>
                                    <input type="text" class="form-control" id="id_titulo" name="titulo">
                                </div>
                                <div class="form-group">
                                    <label for="id_mensagem">Mensagem:</label>
                                    <textarea class="form-control" id="id_mensagem" name="mensagem" rows="5"></textarea>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </form>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
        <script src="js/jquery-3.3.1.min.js"></script>
        <script src="js/popper.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/main.js"></script>
        <script defer=""
            src="https://static.cloudflareinsights.com/beacon.min.js/vedd3670a3b1c4e178fdfb0cc912d969e1713874337387"
            integrity="sha512-EzCudv2gYygrCcVhu65FkAxclf3mYM6BCwiGUm6BEuLzSb5ulVhgokzCZED7yMIkzYVg65mxfIBNdNra5ZFNyQ=="
            data-cf-beacon="{&quot;rayId&quot;:&quot;882d07e6f80172e3&quot;,&quot;version&quot;:&quot;2024.4.1&quot;,&quot;token&quot;:&quot;cd0b4b3a733644fc843ef0b185f98241&quot;}"
            crossorigin="anonymous" style="display: none !important;"></script>
    </main>
    <!-- Footer-->
    <footer class="bg-white py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0">Copyright &copy; Your Website 2023</div>
                </div>
                <div class="col-auto">
                    <a class="small" href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

bunter_app/templates/produtos/produtos.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content />
    <meta name="author" content />
    <title>Bunter</title>
    <link rel="shortcut icon" href="{% static 'homes/img/bunter_logo.png' %}" type="image/x-icon">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- boostrap_css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"   
        rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'contato/stylecss/cont_estilo.css' %}"> -->
    <!-- Css do projeto -->
    <link rel="stylesheet" href="{% static 'produto/stylecss/produt.css' %}">
</head>
<body class="d-flex flex-column">
    <main class="flex-shrink-0">
        <!-- Navigation-->
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'homes/img/bunter_logo.png' %}" width="65em" height="65em" class="d-inline-block align-top" alt="logo bunter_logo"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
                    aria-controls="navbarSupportedContent" aria-expanded="false" 
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'sobre_mim' %}">Sobre a loja</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'produto' %}">Produtos</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'contato' %}">Contato</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        <section class="projects-section bg-light" id="projects">

            <div class="container">
                <h1>Mostruário de Produtos</h1>
                <div class="row" id="produtos-container">
                    {% for produto in produtos %}
                    <div class="col-md-4">
                        <div class="card" style="width: 18rem; margin-bottom: 2em;">
                            <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.descricao }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ produto.descricao }}</h5>
                                <p class="card-text">Código: {{ produto.codigo }}</p>
                                <p class="card-text">Marca: {{ produto.marca }}</p>
                                <p class="card-text">Custo: R$ {{ produto.custo }}</p>
                                <p class="card-text">Preço de Venda: R$ {{ produto.preco_venda }}</p>
                                <a href="{% url 'cadastro_clientes' %}" class="btn btn-primary mais-informacoes">Mais informações</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>

    <footer class="bg-white py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0">Copyright &copy; Your Website 2023</div></div>
                <div class="col-auto">
                    <a class="small" href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'produto/js/pop-up.js' %}"></script>
      <!-- Inclua os arquivos JS do Bootstrap -->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>